apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: winsper-admin
  namespace: default
  labels:
    name: winsper-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: winsper-admin
  template:
    metadata:
      labels:
        name: winsper-admin
    spec:
      containers:
        - name: winsper-admin
          image: gusabary/winsper-admin
          imagePullPolicy: Always
          ports:
            - name: winsper-admin
              containerPort: 7170
