apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: winsper-user
  namespace: default
  labels:
    name: winsper-user
spec:
  replicas: 2
  selector:
    matchLabels:
      name: winsper-user
  template:
    metadata:
      labels:
        name: winsper-user
    spec:
      containers:
        - name: winsper-user
          image: gusabary/winsper-user
          imagePullPolicy: Always
          ports:
            - name: winsper-user
              containerPort: 7180
