apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: winsper-zuul
  namespace: default
  labels:
    name: winsper-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      name: winsper-zuul
  template:
    metadata:
      labels:
        name: winsper-zuul
    spec:
      containers:
        - name: winsper-zuul
          image: gusabary/winsper-zuul
          imagePullPolicy: Always
          ports:
            - name: winsper-zuul
              containerPort: 30525
